### PR TITLE
Adding last_evaluated_key parameter to scan and query for the ability to

### PR DESCRIPTION
**Pull request by mpresh**
implement paging by retrieving partial results.
This gives ability to scan first 100 items, next 100 items, etc.

### CODE REVIEW

**Comment by mpresh** [comment]
Hello Jharrod,

I am curious if you are still planing on contributing to Pynamodb.
I haven't seen any changes over the last 3 plus months.
We use pynamodb very heavily for our development and we would like to be
able to either work with you or to be able to contribute
back to the repo quickly. For example the ability to support
exclusive_Start_key in order to support paging I made a change months ago
and havent really heard back from you since.

Please let me know how much you plan on dedicating to pynamodb in the
future.
If you are not planning on being involved, maybe you can let me contribute
directly to Pynamodb or we will contribute to a forked version of the repo.

Please let me know your thoughts,
Thanks very much,
-Mike



On Thu, Nov 20, 2014 at 4:39 PM, Jharrod LaFon <notifications@github.com>
wrote:

> Thanks for contributing! I also want this feature to be included. I work
> very hard to ensure that PynamoDB is thoroughly tested. Your pull request
> introduces a new feature, but doesn't include any test code. I can merge it
> quickly if you update it to include tests, or it will have to wait until I
> can write some.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jlafon/PynamoDB/pull/48#issuecomment-63884791>.
>



-- 

Mike Preshman - Software Architect/Zen Seeker - 617.653.6638

**Comment by jlafon** [comment]
Hi Mike,

I am still planning to contribute to PynamoDB. My open source contributions have waned as of late because I happily spend most of my free time with my new born son. 

That being said, we also use PynamoDB heavily in production (we just haven't encountered your issue). I'll take a look at this issue again for you.

Finally, I am open to letting other people contribute directly to PynamoDB, but I do insist on thorough unit testing. 

Thanks!

**Comment by jlafon** [comment]
Would you mind trying https://github.com/jlafon/PynamoDB/commit/a104195e12d239874bf858b79b7918932def47a4 and letting me know if that works for you? Thanks.

**Comment by mpresh** [comment]
You have an offset by one issue. You want to move the yield before the
return or otherwise, you return one less item than the limit.

        for item in data.get(ITEMS):

            yield cls.from_raw_data(item)

            if limit is not None:

                limit -= 1

                if not limit:

                    return


The other thing that your code doesnt currently handle that I ran into
during testing this is that we are using the last_evaluated_key parameter
in order to be able to request first 5 items, next 5 items, etc. (paging)

I submitted a pull request with this sometime ago.
https://github.com/jlafon/PynamoDB/pull/48/commits

Otherwise looks good.


-Mike

On Thu, Feb 12, 2015 at 11:36 PM, Jharrod LaFon <notifications@github.com>
wrote:

> Would you mind trying a104195
> <https://github.com/jlafon/PynamoDB/commit/a104195e12d239874bf858b79b7918932def47a4>
> and letting me know if that works for you? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jlafon/PynamoDB/pull/48#issuecomment-74204133>.
>



-- 

Mike Preshman - Software Architect/Zen Seeker - 617.653.6638

**Comment by danielhochman** [comment]
covered by #79 and #135

**Pull request closed without merging**
