### PR TITLE
use range key when not none, otherwise batch get all without range

### PR DESCRIPTION
**Pull request by jmphilli**
allows us to look up all models by hash key when range is defined
```python
identifiers = [(identifier, None) for identifier in identifiers]
for result in model.batch_get(identifiers):
```

### CODE REVIEW

**Comment by jmphilli** [comment]
@garrettheel

**Comment by jmphilli** [comment]
@danielhochman

**Comment by garrettheel** [comment]
Can you add a test for this?

**Comment by jmphilli** [comment]
oh fo sho -- does the api make sense?

**Pull request closed without merging**
