### PR TITLE
Pin Botocore To Working Version

### PR DESCRIPTION
**Pull request by cshoe**
PynamoDB isn't compatible with Botocore 1.0.0. This patch pins PynamoDB to a compatible version. This should serve as a bandaid until PynamoDB can be updated to support 1.0.0.

### CODE REVIEW

**Comment by jlafon** [comment]
Thanks for this. I'm working on botocore 1.0.0 support now, it shouldn't take too long.

**Comment by cshoe** [comment]
:+1: Good to hear!

I was taking a stab at it a couple weeks ago. Here's all the further I got. Not sure if it would be helpful to you at all. https://github.com/jlafon/PynamoDB/compare/devel...cshoe:botocore-1.0.0-support

**Comment by cshoe** [comment]
> it shouldn't take too long

I hate to be that person, but could you provide more detail?

**Comment by jlafon** [comment]
@cshoe would you be interested in testing out 4bbec46?

**Comment by cshoe** [comment]
@jlafon Absolutely. On it now.

**Comment by cshoe** [comment]
@jlafon Appears to be working great.

**Comment by jlafon** [comment]
Great, thanks @cshoe for helping out. I'll put out a new release today.

**Pull request closed without merging**
