### PR TITLE
Make limit inclusive. Add query limit tests.

### PR DESCRIPTION
**Pull request by danielcorreia**
Related to issue [#95](https://github.com/jlafon/PynamoDB/issues/95), which is already closed but doesn't seem to work.

So, this returns the correct number of results. Example: when limit is 5 and there are at
least 5 matches return 5 items.

Hopefully I wrote the tests properly, not very experienced with testing. Please look at it.

Thanks!

### CODE REVIEW

**Comment by LiteWait** [comment]
This really seems to be the wrong fix, this works for me,

     for item in data.get(ITEMS):
            yield cls.from_raw_data(item)
            if limit is not None:
                limit -= 1
                if not limit:
                    return

**Comment by danielcorreia** [comment]
@LiteWait both solutions work if the `limit` is > 0 or `None`.
With that iterator, if the user uses 0 as limit (which doesn't really make sense, I know) the iterator will yield all the items.

**Comment by danielhochman** [comment]
We also need tests for limit logic when `last_evaluated_key` is returned.

**Comment by danielhochman** [comment]
closed in favor of #123 which also fixed limits when there were multiple pages.

thanks for the contribution though!

**Pull request closed without merging**
