### PR TITLE
fix limits

### PR DESCRIPTION
**Pull request by danielhochman**
copied query limit code from @joshowen's fork after a discussion with him over email.

i wrote the tests.

### CODE REVIEW

**Comment by jlafon** [comment]
LGTM. Thanks!

**Comment by Lifto** [comment]
Still having an issue with this, maybe it's not the same thing?

Invalid range for parameter Limit, value: 0, valid range: 1-inf

for code like this:
items = Item.user_index.query(user_key, limit=2)

if limit is 1 I don't get an exception, if limit is 3 or more I don't get an exception.

**Comment by danielhochman** [comment]
@Lifto are you on v1.5.0 or later?

**Comment by Lifto** [comment]
tried on both 1.5.0 and 1.5.1

**Comment by danielhochman** [comment]
@Lifto in the absence of a limit, how many items would that query return?

**Comment by Lifto** [comment]
I would have to check in depth to 100% sure, but my basic expectation is that it would return 1 or 0 items.  When I wanted to get single items from a query I would have to request limit=2, because limit=1 would return nothing, but limit=2 would return the one item. (that was on 1.4.4)

**Pull request merged**
